include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = VirtualCamPro

VirtualCamPro_FILES = VCPRootListController.m
VirtualCamPro_FRAMEWORKS = UIKit Foundation
VirtualCamPro_PRIVATE_FRAMEWORKS = Preferences
VirtualCamPro_INSTALL_PATH = /Library/PreferenceBundles
VirtualCamPro_RESOURCE_FILES = Info.plist
VirtualCamPro_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter

include $(THEOS_MAKE_PATH)/bundle.mk
